# Auto-generated by django-bolt types. Do not edit manually.

from __future__ import annotations
from typing import Optional
from django_bolt.typecheck import TypedQuerySet, TypedManager
from django.db.models import Model

class Session(Model):
    session_key: str
    session_data: str
    expire_date: datetime.datetime
    objects: SessionManager

class SessionQuerySet(TypedQuerySet[Session]):
    def filter(self, *, session_key: Optional[str] = ..., session_data: Optional[str] = ..., expire_date: Optional[datetime.datetime] = ...) -> SessionQuerySet: ...
    def exclude(self, *, session_key: Optional[str] = ..., session_data: Optional[str] = ..., expire_date: Optional[datetime.datetime] = ...) -> SessionQuerySet: ...
    def get(self, *, session_key: Optional[str] = ..., session_data: Optional[str] = ..., expire_date: Optional[datetime.datetime] = ...) -> Session: ...

class SessionManager(TypedManager[Session]):
    def filter(self, *, session_key: Optional[str] = ..., session_data: Optional[str] = ..., expire_date: Optional[datetime.datetime] = ...) -> SessionQuerySet: ...
    def exclude(self, *, session_key: Optional[str] = ..., session_data: Optional[str] = ..., expire_date: Optional[datetime.datetime] = ...) -> SessionQuerySet: ...
    def get(self, *, session_key: Optional[str] = ..., session_data: Optional[str] = ..., expire_date: Optional[datetime.datetime] = ...) -> Session: ...

