# Auto-generated by django-bolt types. Do not edit manually.

from __future__ import annotations
from typing import Optional
from django_bolt.typecheck import TypedQuerySet, TypedManager
from django.db.models import Model

class ContentType(Model):
    app_label: str
    model: str
    objects: ContentTypeManager

class ContentTypeQuerySet(TypedQuerySet[ContentType]):
    def filter(self, *, app_label: Optional[str] = ..., model: Optional[str] = ...) -> ContentTypeQuerySet: ...
    def exclude(self, *, app_label: Optional[str] = ..., model: Optional[str] = ...) -> ContentTypeQuerySet: ...
    def get(self, *, app_label: Optional[str] = ..., model: Optional[str] = ...) -> ContentType: ...

class ContentTypeManager(TypedManager[ContentType]):
    def filter(self, *, app_label: Optional[str] = ..., model: Optional[str] = ...) -> ContentTypeQuerySet: ...
    def exclude(self, *, app_label: Optional[str] = ..., model: Optional[str] = ...) -> ContentTypeQuerySet: ...
    def get(self, *, app_label: Optional[str] = ..., model: Optional[str] = ...) -> ContentType: ...

