# Auto-generated by django-bolt types. Do not edit manually.

from __future__ import annotations
from typing import Optional
from django_bolt.typecheck import TypedQuerySet, TypedManager
from django.db.models import Model

class BenchItem(Model):
    name: str
    value: int
    description: str
    is_active: bool
    created_at: datetime.datetime
    updated_at: datetime.datetime
    objects: BenchItemManager

class BenchItemQuerySet(TypedQuerySet[BenchItem]):
    def filter(self, *, name: Optional[str] = ..., value: Optional[int] = ..., description: Optional[str] = ..., is_active: Optional[bool] = ..., created_at: Optional[datetime.datetime] = ..., updated_at: Optional[datetime.datetime] = ...) -> BenchItemQuerySet: ...
    def exclude(self, *, name: Optional[str] = ..., value: Optional[int] = ..., description: Optional[str] = ..., is_active: Optional[bool] = ..., created_at: Optional[datetime.datetime] = ..., updated_at: Optional[datetime.datetime] = ...) -> BenchItemQuerySet: ...
    def get(self, *, name: Optional[str] = ..., value: Optional[int] = ..., description: Optional[str] = ..., is_active: Optional[bool] = ..., created_at: Optional[datetime.datetime] = ..., updated_at: Optional[datetime.datetime] = ...) -> BenchItem: ...

class BenchItemManager(TypedManager[BenchItem]):
    def filter(self, *, name: Optional[str] = ..., value: Optional[int] = ..., description: Optional[str] = ..., is_active: Optional[bool] = ..., created_at: Optional[datetime.datetime] = ..., updated_at: Optional[datetime.datetime] = ...) -> BenchItemQuerySet: ...
    def exclude(self, *, name: Optional[str] = ..., value: Optional[int] = ..., description: Optional[str] = ..., is_active: Optional[bool] = ..., created_at: Optional[datetime.datetime] = ..., updated_at: Optional[datetime.datetime] = ...) -> BenchItemQuerySet: ...
    def get(self, *, name: Optional[str] = ..., value: Optional[int] = ..., description: Optional[str] = ..., is_active: Optional[bool] = ..., created_at: Optional[datetime.datetime] = ..., updated_at: Optional[datetime.datetime] = ...) -> BenchItem: ...

